Кобяков Сергей
urfu-2017/autotests-task-04 pull request #3
Opened 2018-05-02 08:19 UTC by skobyakov

[Видео](https://drive.google.com/open?id=1vRIvjwZq-la3eU6mm8bup5mNfpIxRSYS)

2018-05-05 05:27 UTC, mrprovoker requested changes

2018-05-05 05:27 UTC, mrprovoker commented on tests/desktop/kilogram-1.js
> +        await browser.click(PO.kilogram.signInBtn);
Сейчас тест не атомарный, его результат зависит от прохождения теста github-1
Если упадет предыдущий тест или его просто удалят - этот тест работать не будет.

Давай сделаем этот тест самостоятельным.

2018-05-09 07:26 UTC, skobyakov commented
[Только тест профиля k1logram](https://drive.google.com/open?id=1yBnVKGWitVQFIboS5e61xYuXPktQ88Rh)
[Оба теста](https://drive.google.com/open?id=145c488LNUdemT_TsSoSWRyM9gIYcxREG)

2018-05-11 16:04 UTC, mrprovoker approved these changes

2018-05-11 16:04 UTC, mrprovoker commented on tests/desktop/kilogram-1.js
> +        if (url.includes(PO.github.loginUrl)) {
по-хорошему в beforeEach проводить проверку и разлогиниваться при необходимости.
(по аналогии с юнит-тестами готовим окружение)

2018-05-11 16:04 UTC, closed without merging